global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
- job_name: 'kafka'
  # metrics_path: "/metrics"
  static_configs:
  - targets:
    - kafka:9998 # JMX exporter
    - kafka-exporter:9308 # kafka exporter
